import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ewuranna Smith-Quayson </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        My Three Birthday Wishes
        </h1>

        <p className={styles.message}> <strong>Hey friend! </strong> Thank you for doing this! <br/> 
        You can do any of these three things to celebrate with me today:<br/> </p>

        <div className={styles.grid}>
          <a href="https://vocal.media/authors/ewuranna-smith-quayson" className={styles.card}>
            <h2 className={styles.section}>Read any of <Link href="https://vocal.media/authors/ewuranna-smith-quayson"><a>My Articles</a></Link> </h2>
            <p>Read and Share the Link with 10 people</p>
          </a>

          <a href="https://www.paypal.com/paypalme/buzzedison" className={styles.card}>
            <h2 className={styles.section}>Send cash &rarr;</h2>
            {/* <p>(because who doesn't like cash right?)</p> */}
            <p> <p><strong>Options:</strong> </p>
              <Link href=""><a>Mobile Money</a></Link> <br/>
            
              <Link href=""><a>Debit Card</a></Link> <br/>
              <Link href="https://www.paypal.com/paypalme/buzzedison"><a>PayPal</a></Link>
              </p>
          </a>

          <a
            href="https://www.kazi.bloopglobal.com"
            className={styles.card}
          >
            <h2 className={styles.section}>Buy from any of these businesses &rarr;</h2>
            <p>

            <Link href="https://www.justfreshonline.com/juices"><a>Just Fresh (Juices)</a></Link> <br/>
            
            <Link href="https://www.pricelezz.co'"><a>Pricelezz</a></Link> <br/> <span className={styles.deal}>A website or ecommerce shop 
            at a really good deal</span> <br/>
            
            
            </p>
          </a>

         
        </div>
        <under>
        <p className={styles.under}>Thanks again for doing this!</p> <br/>
         <span className={styles.love}>Love,<br/>
         Ewuranna.</span>
        </under>
      </main>

      <footer className={styles.footer}>
       <h2> Ewuranna Smith-Quayson (c) 2022</h2>
      </footer>
    </div>
  )
}
